### ISSUE TITLE
Got "failed" result when run "mvn verify"

### ISSUE THREAD

**Issue by fm365** [SparkTC/systemml#77]
My environment is : Win7 + R x64 3.1.2 + maven 3.2.3 + java 1.8 

When run "mvn verify" , I got the following error:

[INFO]
[INFO] --- exec-maven-plugin:1.1.1:java (default) @ system-ml ---
Installing packages required for running integration tests ...
The system cannot find the path specified.
java.lang.Exception: ERROR: R has ended irregularly

script file: .\src\test\scripts\installDependencies.R
        at com.ibm.bi.dml.utils.InstallDependencyForIntegrationTests.runRScript(InstallDependencyForIntegrationTests.java:91)
        at com.ibm.bi.dml.utils.InstallDependencyForIntegrationTests.main(InstallDependencyForIntegrationTests.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:283)
        at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:19 min
[INFO] Finished at: 2015-12-06T16:03:05+08:00
[INFO] Final Memory: 78M/751M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1.1:java (default) on project system-ml: An exception occured while
ed to run script .\src\test\scripts\installDependencies.R
[ERROR] exception: java.lang.Exception: ERROR: R has ended irregularly
[ERROR]
[ERROR] script file: .\src\test\scripts\installDependencies.R
[ERROR] message: ERROR: R has ended irregularly
[ERROR]
[ERROR] script file: .\src\test\scripts\installDependencies.R
[ERROR] stack trace:
[ERROR] >com.ibm.bi.dml.utils.InstallDependencyForIntegrationTests.runRScript(InstallDependencyForIntegrationTests.java:91)
[ERROR] >com.ibm.bi.dml.utils.InstallDependencyForIntegrationTests.main(InstallDependencyForIntegrationTests.java:39)
[ERROR] >sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] >sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] >sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] >java.lang.reflect.Method.invoke(Method.java:497)
[ERROR] >org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:283)
[ERROR] >java.lang.Thread.run(Thread.java:745)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Who knows how to fix it ?

**Comment by mboehm7** [comment]
@fm365 this repository is not maintained any longer as we moved to https://github.com/apache/incubator-systemml. Could you please post your issue at our mailing list dev@systemml.incubator.apache.org - this would help other developers too who run into the same issue. Thanks.
